name: api

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  IMAGE_NAME: api

jobs:
  push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --file "./${IMAGE_NAME}.Dockerfile" --tag $IMAGE_NAME

      - name: Log into GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[A-Z]' '[a-z]')
          REPO=$(echo "${{ github.event.repository.name }}" | tr '[A-Z]' '[a-z]')
          IMAGE_ID="ghcr.io/${OWNER}/${REPO}/${IMAGE_NAME}"

          # Extract version from ref
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip leading v from tag
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo "$VERSION" | sed -e 's/^v//')

          # Use Docker `latest` convention for main
          [ "$VERSION" == "main" ] && VERSION=latest

          echo "IMAGE_ID=$IMAGE_ID"
          echo "VERSION=$VERSION"

          docker tag $IMAGE_NAME $IMAGE_ID:${{ github.sha }}
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION

          docker push $IMAGE_ID:${{ github.sha }}
          docker push $IMAGE_ID:$VERSION
